"""
Django settings for SocialMediaApp project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os

# 1. المسارات الأساسية
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. إعدادات الأمان (خلى الـ DEBUG بـ False لما تخلص خالص وتجرب)
SECRET_KEY = "django-insecure-v6hx=05v-iwcfm%7fba4m95vfmf+9&%q+sdyp)(sb32$11@0d4"
DEBUG = True 

# 3. تعديل الـ ALLOWED_HOSTS عشان يشتغل على اسمك الجديد "gouda"
ALLOWED_HOSTS = ['gouda.pythonanywhere.com', 'localhost', '127.0.0.1']

# 4. تعريف الـ Apps والمكتبات
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
    "crispy_bootstrap4",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SocialMediaApp.urls"

# 5. القوالب (Templates)
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'Templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SocialMediaApp.wsgi.application"

# 6. قاعدة البيانات (SQLite)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# 7. الـ Auth (تأكد إن الموديل ده موجود في core)
AUTH_USER_MODEL = 'core.User'

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 8. اللغة والوقت
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# 9. إعدادات الـ Static والـ Media (مهمة جداً للرفع)
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

STATIC_URL = "static/"
# المكان اللي السيرفر هيجمع فيه الملفات (للسيرفر فقط)
STATIC_ROOT = BASE_DIR / "staticfiles"
# المكان اللي أنت حاطط فيه ملفاتك دلوقتي
STATICFILES_DIRS = [BASE_DIR / "Static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"