# Generated by Django 5.2 on 2025-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_created",
            new_name="created_date",
        ),
    ]
