# Generated by Django 5.2 on 2025-11-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_friends"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Friends",
            new_name="Friend",
        ),
    ]
